### ISSUE TITLE
reference to user in Post Schema

### ISSUE THREAD

**Issue by MuhammadIsmail-Dev** [bradtraversy/devconnector_2.0#101]
reference to the user in Post Schema is 'users' but it needs to be 'user' in likes, comments, and post as well

**Comment by bushblade** [comment]
Hi @MuhammadIsmail-Dev 
No it should reference the collection in the database.
The model is 'user' which mongoose pluralizes to create the collection. So in the collection in the database it is 'users'.
There is no issue I can see here so I'll close.
