### ISSUE TITLE
Reducing lines of code

### ISSUE THREAD

**Issue by yashu2001** [bradtraversy/devconnector_2.0#104]
Hey Brad first off a big shout out to you to provide us with such amazing courses so easy to understand and learn.I would like to propose a small enhancement to the API handling functions.
I'd rather run a for in loop than destructuring.Anyways you know whats best and do let me know if you would like to me submit a pr on that I'll get working on it.

**Comment by bushblade** [comment]
Hi @yashu2001 
Can you give an example of the changes and how this will improve the application?

**Comment by bushblade** [comment]
I've not heard back from you and there is no issue here currently, so I'll close.
If you want to come back with your suggestions or PR for review, please do so.
