### ISSUE TITLE
I dont see where do you set the token in auth state after response from server

### ISSUE THREAD

**Issue by andreasdevjs** [bradtraversy/devconnector_2.0#105]
Hello! In the old code of this repository you can see how you set the token in the state once you receive it from the request. I don't see it being done anywhere now.. Is it just me that doesn't see it? Thank you very much for this magnificent example! (I am a paying student)

**Comment by bushblade** [comment]
Hi @andreasdevjs 
This is now handled in a redux subscription.
[See the notes as to why we do this here in the README](https://github.com/bradtraversy/devconnector_2.0#redux-subscription-to-manage-local-storage)
For any course questions please post in the course Q&A and one of us will get to you shortly.
I'll close this as an issue.
