### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by hainsdominic** [bradtraversy/devconnector_2.0#106]
client/src/actions/profile.js:236

pemanantly should be spelled permanently.

Thanks for your great course.

**Comment by bushblade** [comment]
Hi @hainsdominic 
Thanks for letting us know, nice spot.
Would you like to submit a pull request with the change?
I can do it but I'm aware many of Brad's students may not have had the opportunity to submit a pull request before, so something simple like this change may be appealing to you?
No worries if not.

**Comment by bushblade** [comment]
Fixed in #109
