### ISSUE TITLE
Found a bug on Register/Login

### ISSUE THREAD

**Issue by iamaul** [bradtraversy/devconnector_2.0#107]
I've been following this course since this course was updated. There's a bug I've found on user authentication. So, when you're registering or logging in you'll be redirected to the login page, not the dashboard page and returns 401 (Authorization denied). It means that the headers aren't received a token nor the token is null. Any idea?

**Comment by bushblade** [comment]
Hi @iamaul 
Does this occur with your own code, or with the code here in the repository?
Have you cloned the repo and tried replicating the issue?

**Comment by iamaul** [comment]
I wrote my own project and currently is developing user authentication using this repo (Register/Login redux). Just so you know, I deployed backend API with port 5000 and I've already set these request headers.

```
app.use(function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-auth-token");
    next();
});
```

**Comment by bushblade** [comment]
If this isn't an issue with the repository code then I'll close this as an issue here on GitHub.
For help with your own project's I would advise chatting on a good Discord server or asking on another platform like StackOverFlow.
I would not recommend setting those headers in your backend app as you're allowing any application to use your api, with if you value your clients details then is a really bad idea.
