### ISSUE TITLE
Loading property in initialState never go back to true?

### ISSUE THREAD

**Issue by LeonelCurti** [bradtraversy/devconnector_2.0#108]
In reducers/auth.js  the loading property once false never go back to true in any action?

anyone else detect this?

**Comment by bushblade** [comment]
Hi @LeonelCurti 
Yeah I think you're correct.
Loading only needs to be true for when the app first runs when a user visits the site or refreshes the browser. So we don't need to explicitly set it back to true at any time during the users session.
Hope that makes sense.
I'll close this as an issue.
