### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by Nishthavan** [bradtraversy/devconnector_2.0#112]
I am not able to deploy on heroku whereas it runs on local machine

**Comment by bushblade** [comment]
Hi Nishtaven.
Is this an issue you're having with your own code or the current repository code?
If you're taking Brad's course then please post in the course Q&A.
Some things to check though..
Does the app run in production locally?
[You can read how to run a production build here](https://github.com/bradtraversy/devconnector_2.0#test-production-before-deploy)
Check that your mongoDB Atlas database has not whitelisted IP access on your production database.
Read the error output. 
Read the Heroku logs
```
heroku logs --tail
```
From the error you're posting in the title however, I can see that you have a case in your backend where you're trying to send back more than one response from a route handler. Which means you most likely forgot to return a res somewhere in a conditional.
As this isn't an issue with the repository code, I'll close as an issue here on GitHub.

**Comment by Nishthavan** [comment]
it is the repository code and app runs locally

**Comment by bushblade** [comment]
Ok can you explain the steps to take to reproduce the error so I can investigate?

**Comment by Nishthavan** [comment]
i downloaded the code and just proceed with the steps given runs perfectly on my local machine but not able to deploy 
My own code was also doing the same thats why i tried to download from here and still the same results

**Comment by bushblade** [comment]
Where is it you're seeing the error on production?

**Comment by Nishthavan** [comment]
It is coming in console even when IAM running locally but still the website is running perfectly each and every functionality

**Comment by Nishthavan** [comment]
So I guess this error is not make difficulty at local stage but at time of deployment it is

**Comment by bushblade** [comment]
Whic page, route, requests cause the issue?

**Comment by Nishthavan** [comment]
That Iam not sure of

**Comment by bushblade** [comment]
Please, there must be some page, route or request you make that produces the issue, what is that. I need to be able to replicate it to fix it.

**Comment by bushblade** [comment]
I have been through the application and can find no such error.
Without sufficient information or being able to replicate any issue I will have to close.

**Comment by Nishthavan** [comment]
i got the problem it was showing a problem with a package 'nan' we have to install it independently than - npm install - on the root folder of the project we have to do:-
npm i nan

**Comment by Nishthavan** [comment]
then the headers problem is not coming
