### ISSUE TITLE
Register/Login issue

### ISSUE THREAD

**Issue by AnjasaDatta** [bradtraversy/devconnector_2.0#113]
When i am trying to login / register a user from the front end,LOGIN_SUCCESS/REGISTER_SUCCESS action is dispatched in the redux dev tools. But the user state is not updating.The previous user state is coming whereas in USER_LOADED and LOGOUT action,user state is coming correctly.Can you please tell me this issue?

**Comment by bushblade** [comment]
Hi @AnjasaDatta 
Is this an issue you're facing with your own code or with the current code in the repository?

**Comment by Yariandres** [comment]
Having the same issue...

**Comment by AnjasaDatta** [comment]
Hi @bushblade ,
In the repository code,in auth reducer for case REGISTER_SUCESS the user is set to payload,so returning the token in user data but if i only return the {...payload} then it comes the prev data(prev user who log out)  and in case of LOGIN_SUCESS,it is showing the prev data(prev user who log out) of the user .

**Comment by bushblade** [comment]
Hi again.
I think I understand what you're saying yes.
So currently we have..
```js
    case REGISTER_SUCCESS:
      return {
        ...state,
        ...payload,
        isAuthenticated: true,
        loading: false,
        user: payload
      };
```
Which should be..
```js
    case REGISTER_SUCCESS:
      return {
        ...state,
        ...payload,
        isAuthenticated: true,
        loading: false
      };
```
After a logout though a user would be null, I do think the above needs to be changed though yes,

**Comment by bushblade** [comment]
Can you pull down the changes and check if that is working as expected for you?

**Comment by AnjasaDatta** [comment]
Hi again,
I pull down the changes and tried to run but again coming the same... in USER_LOADED action,the user data is coming correctly and in LOGOUT action also...But in LOGIN/REGISTER,the user data is coming wrong.
I also tried with this also like set the token in local store  but also nothing works...

case REGISTER_SUCESS:
    case LOGIN_SUCESS:
      localStorage.setItem('token', payload.token);
      return {
        ...state,
        ...payload,
        //user: payload,
        isAuthenticated: true,
        loading: false,
      };
Can you please help me......

**Comment by bushblade** [comment]
Can you just confirm that you are testing the current repository code? You shouldn't be setting local storage in reducers as that breaks redux's rules. Reducers should be pure functions.

**Comment by bushblade** [comment]
As I haven't heard anything back from you and I cannot reproduce any further issue since 
11e4b3b  then I'll close.

**Comment by adarshaacharya** [comment]
Hi, @bushblade this issue is still occuring . REGISTER_SUCCESS action gets dispatched but can't get the user. AUTH_ERROR action gets immediately.

![image](https://user-images.githubusercontent.com/50266088/85387339-6b504080-b564-11ea-9e5c-41f58c2ae7a9.png)

**Comment by bushblade** [comment]
Hi again @adarshaacharya 
Can you confirm that you are using the current repository code?

**Comment by adarshaacharya** [comment]
@bushblade yes.. I'm following the code in this repo.

**Comment by bushblade** [comment]
Hi again I can't reproduce this issue with the current repository code.
When you say you're following the code in this repo what does that mean?
Please make sure you are using the current code from the master branch.
Clone the repository, add your config/default.json and test that. Do you still get the issue?

**Comment by adarshaacharya** [comment]
@bushblade  sir Can you tell me one explannation from this current code. Where do we actually put the "token" in localstorage. After login/signup there is no such code to save the token received in payload to the localstorage.

**Comment by bushblade** [comment]
Please have a read of the [notes in the README](https://github.com/bradtraversy/devconnector_2.0#redux-subscription-to-manage-local-storage-) 
This is now handled in a redux subscription.

**Comment by ishank-dev** [comment]
@AnjasaDatta 
I had the same issue and I got it fixed by changing my MongoDB URL by putting node version as ``2.2.1 or later`` I got a bigger string of URL.
The reason it was happening is mentioned in this StackOverflow thread https://stackoverflow.com/questions/55794145/mongonetworkerror-connection-3-to-cluster0-shard-00-02-z0urk-mongodb-net27017
You get this error while registering through postman also.

**Comment by ngc7023** [comment]
@adarshaacharya Hi, I met the same problem. Do you managed to solve it?
