### ISSUE TITLE
Type error cannot read property _id of null

### ISSUE THREAD

**Issue by Muizuddeen** [bradtraversy/devconnector_2.0#117]
Everything is working fine in my redux, functions is firing. When i refresh my page in get all profiles ,i get this error.I have checked my code 10 times.

**Comment by bushblade** [comment]
Hi @Muizuddeen 
Is this an issue with your own code, or the current code in the repository?
If it's an issue with the current repo code then please post your error output and carefully explain the steps you take to reproduce the error.

**Comment by Muizuddeen** [comment]
![Uploading IMG_20200506_205211.jpg…]()
![Uploading IMG_20200506_205336.jpg…]()
This is the error, .

**Comment by Muizuddeen** [comment]
![Uploading IMG_20200506_205211.jpg…]()

**Comment by Muizuddeen** [comment]
![Uploading IMG_20200506_205211.jpg…]()

**Comment by bushblade** [comment]
Hi again.
I'm still not sure as to if what your issue is, if it's with your own code or the repository code or the steps to reproduce the issue.
I see that you've closed the issue now anyway.

**Comment by Muizuddeen** [comment]
https://github.com/Muizuddeen/DevSocialConnector

when i go to profile route for get all profiles it gives error  Unhandled Rejection (TypeError): Cannot read property 'statusText' of undefined

(anonymous function)
C:/Users/user/Desktop/DevConnector/client/src/actions/profile.js:45
  42 | } catch (err) {
  43 |   dispatch({
  44 |     type:PROFILE_ERROR,
> 45 |     payload: {msg: err.response.statusText, status: err.response.status}
  46 |   });
  47 |   }
  48 | };

**Comment by bushblade** [comment]
Once again, is this an issue with your own code or with the repository code?

**Comment by Muizuddeen** [comment]
own code but why are giving this error please check my code

**Comment by bushblade** [comment]
If it's not a problem with this repository then this isn't the right place to raise an issue. If you are a Udemy student of Brad's the please post in the course Q&A and one of us can help you out.
