### ISSUE TITLE
Issue on rendering components

### ISSUE THREAD

**Issue by AnjasaDatta** [bradtraversy/devconnector_2.0#118]
Hi,
As i am adding a new exp,the below error is showing but i can see in redux dev tools,the experience is getting added in the profile.When i am refreshing the page,the dashboard page comes with the new exp added to the table..Can you please tell me how to resolve the issue.I cannot able to find.I know that the value is not rendering but can't able to figure out where is the issue......

![capture_20200510162717](https://user-images.githubusercontent.com/54656819/81497391-d78c2300-92db-11ea-8c3f-815d243a5072.png)

**Comment by bushblade** [comment]
Hi @AnjasaDatta 
Is this an issue with your own code or the code here in the repository?

**Comment by AnjasaDatta** [comment]
the issue is with my own code

**Comment by bushblade** [comment]
Hi again.
If this isn't an issue with the current repository code, then isn't really the place to raise an issue.
If you're a student of Brad's then please post in the course Q&A and one of us will get to you soon.
If you just need a working project then please clone the repository and use that.
I'll close this as an issue.
