### ISSUE TITLE
Proxy error: Could not proxy request /api/auth from localhost:3000 to http://localhost:5000.

### ISSUE THREAD

**Issue by kenkiyoshi** [bradtraversy/devconnector_2.0#121]
`export const loadUser = () => async (dispatch) => {
  if (localStorage.token) {
    setAuthToken(localStorage.token);
  }

  try {
    const res = await axios.get("/api/auth");

    dispatch({
      type: USER_LOADED,
      payload: res.data,
    });
  } catch (err) {
    dispatch({
      type: AUTH_ERROR,
    });
  }
};`

**Comment by bushblade** [comment]
Hi @kenkiyoshi 
This doesn't look like current repository code.
If you are a student of Brad's and need help then please post a question in the course Q&A and one of us will help you out.
If you just need a working project, then please clone or fork the current repository.
