### ISSUE TITLE
Redux state updates back to previous state

### ISSUE THREAD

**Issue by kk-ssc** [bradtraversy/devconnector_2.0#127]
My redux state updates back to previous state on logging out.

Series of events:

1. I log out, and it takes me to the login screen

2. I reload the page, I have no access which is correct.

3. I go back from browser tab and then again go forward I have access and the isAuthenticated state again becomes "true" with user data loaded. 

4. Sometimes but not always it loads when I load the URL localhost:3000

How is this possible?

I have checked my local storage there is no such data stored.

Screenshots:

![logout](https://user-images.githubusercontent.com/60385191/83236350-0433ac00-a1b1-11ea-84cf-8940d7d419e4.png)
![loginback](https://user-images.githubusercontent.com/60385191/83236354-0564d900-a1b1-11ea-9417-94032305501d.png)

**Comment by bushblade** [comment]
Hi @kk-ssc 
Is this an issue with your own code or with the code from this repository?
Does this occur in development or production or both?

**Comment by kk-ssc** [comment]
Issue with my code I have used store.js as well for subscribing all events. 

It occurs in development. It is not in production stage

**Comment by bushblade** [comment]
If this is not an issue with the code here in the repository I'll close then.
If you're facing an issue with course code then please post in the course Q&A and one of us will help you out.
