### ISSUE TITLE
getting there error and can't resolve it please help

### ISSUE THREAD

**Issue by archana23499** [bradtraversy/devconnector_2.0#128]
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
(node:19496) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [Bus]. Use emitter.setMaxListeners() to increase limit
(node:5548) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Server started on port ${PORT}
Password contains an illegal unescaped character
[nodemon] app crashed - waiting for file changes before starting...

**Comment by bushblade** [comment]
Hi @archana23499 
This shouldn't be an issue as we have `useNewUrlParser: true` in [config/db.js](https://github.com/bradtraversy/devconnector_2.0/blob/master/config/db.js).
As to your connection issue, obviously your database connection string is up to you to provide a valid connection to your database. The repository code doesn't include a database.
I am assuming that this is an issue with your own code, as it doesn't match the repository code. So I'll close as an issue.
If you're a student of Brad's then please post in the course Q&A and one of us will help you out, if you just need a working application, clone and run the latest code in this repository and make sure to provide your own database config/default.json.
