### ISSUE TITLE
A small bug in profile.js

### ISSUE THREAD

**Issue by gsc2001** [bradtraversy/devconnector_2.0#130]
The line 71 in profile.js has a error. If website is undefined therefore the condition fails therefore wesite gets set to '' (an empty string ) (not undefined) therefore it is updated in the db.

**Comment by gsc2001** [comment]
Can i be assigned to this

**Comment by gsc2001** [comment]
On assessing further i found that its the problem with all the fields as the will be set to null if they are not there.
If that is the case then this issue is not needed

**Comment by gsc2001** [comment]
![image](https://user-images.githubusercontent.com/56212978/83678441-61898c00-a5fb-11ea-88a5-122941634fb0.png)
As seen here if i dont provide any not important information. It is set to null. If the project structure is like this only than its not needed

**Comment by bushblade** [comment]
Ok I think I understand, but in what case would we not send all the fields? Even if we send the same values as they were last time. Our client gets all the fields when we fetch a users profile and sends all the fields when we update a profile.

**Comment by gsc2001** [comment]
Like if the person is not interested in giving his/her social handles or doesnt have a specific social account

**Comment by bushblade** [comment]
Then they just won't change it from what it was before and it will stay the same as it was before.

**Comment by gsc2001** [comment]
If the person does not give the information even the first time. Or is there something to make a person enter each information on the first time

**Comment by bushblade** [comment]
If they don't enter the information the first time then it will be an empty string.

**Comment by bushblade** [comment]
I'll close this as I'm not sure I see any issue here, though if you no have a good idea how to handle this better then please submit a PR and I'll review it.
