### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by tichnas** [bradtraversy/devconnector_2.0#131]
In original course code `App.js` there is an if statement (line 15-17) which is not there in the latest code.
I think it is useless because, anyway, we are calling `loadUser()` which will do the same.
Is it safe to remove that condition keeping everything else the same as the original course code?
Thanks

**Comment by bushblade** [comment]
Hi @tichnas yes that's correct as we have pretty much the same logic in utils/setAuthToken.js.
