### ISSUE TITLE
First of all I am very thankful to your help you done a great job for developer Sir,..Sir I face problem when I deploy on heroku, I followed same steps as you suggested but still facing issue

### ISSUE THREAD

**Issue by Mudasirrr** [bradtraversy/devconnector_2.0#133]
Deploy message is successful but when i open then it say  Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by bushblade** [comment]
Hi @Mudasirrr 
Is this an issue with your own code or with the code here in the repository?
Have you checked the Heroku logs? They're usually pretty useful.

**Comment by Mudasirrr** [comment]
Hi @bushblade 

Thanks for your response , I check Heroku logs, Actually it was an error in my package.json file identation mistake.. 
Its resolved.
