### ISSUE TITLE
connecting Mongodb with mongoose

### ISSUE THREAD

**Issue by Puja7629** [bradtraversy/devconnector_2.0#134]
When I try to connect MongoDB with mongoose I get this error:

(node:17936) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Server started on port 5000
Password contains an illegal unescaped character

Please help me out.

**Comment by bushblade** [comment]
Hi @Puja7629 
I'm guessing this is with your own code and not the repository code?
As in the repo code we already have..
```js
await mongoose.connect(db, {
			useNewUrlParser: true,
			useCreateIndex: true,
			useFindAndModify: false,
			useUnifiedTopology: true
		});
```
So yeah do as the warning states and add in `useNewUrlParser: true` to your mongoose.connect config.

**Comment by Puja7629** [comment]
Thanks for your response @bushblade but all the points you mentioned I cross-checked it again and definitely there is no problem in the repo I just need help while building this project I see the URL I copied from cloud.mongodb for establishing a connection ; 

URL: mongodb+srv://puja7629:<password>@linkedin-lite-kyd7o.mongodb.net/<dbname>?retryWrites=true&w=majority

In your tutorial, I just replaced <password> with my password but in the place of <dbname> which dbname I should replace it by the db.js file or the name which I used in the MongoDB site while creating project name.

P.S: <dbname> was not covered in the video lecture so being a novice I am trying to understand things from very scratch.

**Comment by Puja7629** [comment]
Thanks for your response @bushblade but all the points you mentioned I cross-checked it again and definitely there is no problem in the repo I just need help while building this project I see the URL I copied from cloud.mongodb for establishing a connection ; 

URL: mongodb+srv://puja7629:<password>@linkedin-lite-kyd7o.mongodb.net/<dbname>?retryWrites=true&w=majority

In your tutorial, I just replaced <password> with my password but in the place of <dbname> which dbname I should replace it by either by db.js file or the name which I used in the MongoDB site while creating project name.

P.S: <dbname> was not covered in the video lecture so being a novice I am trying to understand things from very scratch.

**Comment by Puja7629** [comment]
Thanks for your response @bushblade but all the points you mentioned I cross-checked it again and definitely there is no problem in the repo I just need help while building this project I see the URL I copied from cloud.mongodb for establishing a connection ; 

URL: mongodb+srv://puja7629:"password"@linkedin-lite-kyd7o.mongodb.net/"dbname"?retryWrites=true&w=majority

In your tutorial, I just replaced "password" with my password but in the place of "dbname" which dbname I should replace it by the db.js file or the name which I used in the MongoDB site while creating project name.

P.S: <dbname> was not covered in the video lecture so being a novice I am trying to understand things from very scratch.

**Comment by bushblade** [comment]
Hi again.
dbname would be what you called your database in MongoDB Atlas, I don't know what you called it.
When you click connect > connect your application it will tell you what you need for the connection string.

Are you taking Brad's Udemy course?

**Comment by Puja7629** [comment]
Yes. @bushblade 
You are right I did that only. I wish I could post the screenshot of my MongoDB Atlas URL and It is clearly written that 

"Replace "<password>" with the password for the puja7629 user. Replace "<dbname>" with the name of the database that connections will use by default. Ensure any option params are URL encoded.

In my code when  I try to replace the dbname with the name which I mentioned in the MongoDB Atlas It is not getting connected and  In the course of Brad's Udemy course the, when he connects with the application and link generated from MongoDB Atlas that is used in default.json file It was not the type of URL I am seeing in an updated version of MongoDB.
It's very minor issue for you but as a beginner, I am just facing small challenges.
Hope you understood the issue I am facing :)

**Comment by Puja7629** [comment]
Yes. @bushblade
You are right I did that only. I wish I could post the screenshot of my MongoDB Atlas URL and It is clearly written that

"Replace "password" with the password for the puja7629 user. Replace "dbname" with the name of the database that connections will use by default. Ensure any option params are URL encoded.

In my code when I try to replace the dbname with the name which I mentioned in the MongoDB Atlas It is not getting connected and In the course of Brad's Udemy course the, when he connects with the application and link generated from MongoDB Atlas that is used in default.json file It was not the type of URL I am seeing in an updated version of MongoDB.
It's a very minor issue for you but as a beginner, I am just facing small challenges.

Hope you understood the issue I am facing :)

**Comment by Puja7629** [comment]
Yes. @bushblade I am taking that course only now.
You are right I did that only. I wish I could post the screenshot of my MongoDB Atlas URL and It is clearly written that

"Replace "password" with the password for the puja7629 user. Replace "dbname" with the name of the database that connections will use by default. Ensure any option params are URL encoded.

In my code when I try to replace the dbname with the name which I mentioned in the MongoDB Atlas It is not getting connected and In the course of Brad's Udemy course the, when he connects with the application and link generated from MongoDB Atlas that is used in default.json file It was not the type of URL I am seeing in an updated version of MongoDB.
It's a very minor issue for you but as a beginner, I am just facing small challenges.

Hope you understood the issue I am facing :)

**Comment by bushblade** [comment]
Yeah I understand that.
What did you call your database then in MongoDB Atlas?

**Comment by bushblade** [comment]
For example I called min devconnector
![Screenshot_2020-06-18_16-27-35](https://user-images.githubusercontent.com/21976188/85040441-b93e0080-b180-11ea-884c-93474ddd0a09.png)
So in my string...
`mongodb+srv://development:<password>@devconnector-5elxe.mongodb.net/<dbname>?retryWrites=true&w=majority`
I replace `<dbname>` with `devconnector`

**Comment by Puja7629** [comment]
Okay.
I named it as "LinkedIn-Lite"

**Comment by bushblade** [comment]
So that's the name you use instead of `<dbname>`

**Comment by bushblade** [comment]
Did you use uppercase or lowercase? I wouldn't use uppercase in your connection string or database name. 
In your OP though the error message claims the password is incorrect, stating illegal characters in the string, are you sure you have that correct?

**Comment by Puja7629** [comment]
I just restarted my system now after replacing the "dbname" with actual dbame "LinkedIn-Lite" and it's working completely fine.
Here is the snapshot, Thank you very much @bushblade :)

![Screenshot from 2020-06-18 22-16-51](https://user-images.githubusercontent.com/43573228/85048948-aa237680-b1b1-11ea-9947-d157cf233238.png)

**Comment by bushblade** [comment]
No problem.
If you need any further help it's probably best to get hold of one of the helpers in the course Q&A.

**Comment by Puja7629** [comment]
Okay, thanks for the guidance sir.
