### ISSUE TITLE
update application for useNewUrlParser: true to connect mongo db

### ISSUE THREAD

**Issue by abhi10agarwal** [bradtraversy/devconnector_2.0#135]

**Comment by bushblade** [comment]
Hi @abhi10agarwal 
Can you elaborate?
What's the issue you've found?
There is very little information  to go on here.

**Comment by abhi10agarwal** [comment]
yes even after using "useNewUrlParser: true," getting below error

 code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5000

**Comment by abhi10agarwal** [comment]
Issued Resolved more than one process running on same 500, thnx for the quick response.
