### ISSUE TITLE
gravatar.url is not a function

### ISSUE THREAD

**Issue by abhi10agarwal** [bradtraversy/devconnector_2.0#136]
even after using below normalize-url module
	const avatar = normalize(
				gravatar.url(email, {
					s: '200',
					r: 'pg',
					d: 'mm'
				}),
				{ forceHttps: true }
			)

getting error : "gravatar.url is not a function"

@bradtraversy @bushblade 
Please provide some tip to get rid of this

**Comment by bushblade** [comment]
Hi @abhi10agarwal 
This isn't an issue with the repository code.
Are you a student of Brad's?
If so can you post a question in the course Q&A and one of us will help you out.
If `gravatar.url` is not a function in your code then I would check that you have required the gravatar module in your file and you have no typo's there.
I'll close as an issue, as it's not an issue with the repo code.
