### ISSUE TITLE
Everytime i make a little change in client files and save it, it automatically logouts me everytime.

### ISSUE THREAD

**Issue by svikas641** [bradtraversy/devconnector_2.0#138]
It is not happening in the production build, is it related to my pc configurations? Its tiring to login everytime and move to the route where i changed the code.

**Comment by elangosundar** [comment]
@svikas641 Hope already added the solution in Course Q&A section. Just go there and search it.

**Comment by svikas641** [comment]
@elangosundar I haven't bought the course so i can't check that out, can you answer me here?

**Comment by bushblade** [comment]
Hi @svikas641 
Is this your own project or are you using the current code in this repository?

**Comment by svikas641** [comment]
Hello @bushblade 
I am using the current code from this repository.

**Comment by bushblade** [comment]
That's strange I can't reproduce that issue.
Can you tell us how you're running the development server,
what OS you're using,
your node version,
your browser,
if your using a private browsing session.

**Comment by svikas641** [comment]
Well i got it, I ran the full application in a higher end pc, it's working fine. My system is slow and kinda old.
