### ISSUE TITLE
Destructure element

### ISSUE THREAD

**Issue by Behnazz** [bradtraversy/devconnector_2.0#146]
https://github.com/bradtraversy/devconnector_2.0/blob/02c0f437cab2d43d8194f733f66612832a9cb1c5/client/src/components/profile-forms/AddEducation.js#L87

As current is destructured at the top I don't think it needs formData.current it can be only current

  setFormData({ ...formData, current: !current })

**Comment by Behnazz** [comment]
@bushblade

**Comment by bushblade** [comment]
@Behnazz thanks, nice spot.
Do you want to submit a PR?

**Comment by Behnazz** [comment]
@bushblade sure I will asap

**Comment by bushblade** [comment]
First you need to fork this repository. Then clone the fork to you local machine, make the changes, add, commit and push to the fork. Then back in GitHub in your forked repo open a PR from there.

**Comment by Behnazz** [comment]
Done ✅

**Comment by bushblade** [comment]
Fixed in #147
