### ISSUE TITLE
logout doesn't change authLink to guestLink

### ISSUE THREAD

**Issue by MohsenKazemizade** [bradtraversy/devconnector_2.0#150]
hello, thanks for this tutorial
I am just in the middle of it, at episode (Logout & navbar links) when I want to logout all is fine, isAuthenticated turn to false, but at navbar, just Logout link is still there.it won't change to guestLink. it will fix when I do refresh.
I checked, my code is exactly as same as brad's, am I miss something?

**Comment by MohsenKazemizade** [comment]
and one more thing:
after clicking on logout at Redux DevTools->state, the token is null, isAuthenticated is false but the user is still there.
I know its not repo, I just want to find out why it happened while in the video there is no problem like this
need help to learn

**Comment by bushblade** [comment]
Hi @MohsenKazemizade 
It sounds like you're one of Brad's students and following along with the Udemy course?
If you can post in the course Q&A with a link to your project's repository then myself or one of the other helpers can look into this for you.
I'll close here in GitHub as this isn't a issue with the repository code.
