### ISSUE TITLE
Proxy error: Could not proxy request /api/users from localhost:3000 to http://localhost:5000.

### ISSUE THREAD

**Issue by AbdellahBrache** [bradtraversy/devconnector_2.0#151]
Hello,
I am having a problem in runing devConnector I have watched the course but when I cloned Brad's repo I tried to run it on my machine and I get "Proxy error: Could not proxy request /api/users from localhost:3000 to http://localhost:5000." I could not figure out the cause of this.
can any help me ?
PS : node v12.18.2

**Comment by bushblade** [comment]
Hi Abdellah.
There could be any number of reasons why this is happening for you.
From the sounds of it though your server is not running or not responding to the client.
So most likely you have some additional error output in the terminal too.
Have you made sure to follow the README and set up your database and config file?
As this isn't an issue with the repository code, I'll close here on GitHub.
If you need help with your course code then please post in the course Q&A and one of us will help you out.

**Comment by AbdellahBrache** [comment]
Hey Bushblade, 
I am taking the course on oreilly and I can't find where I can out my comment that why I have posted this comment here and Yes I have made everything the README and still get the same problem

**Comment by bushblade** [comment]
Ah right. I wasn't aware of O'reily or that Brad was using the platform.
If you post a link to you your project's repository I can take a look for you and see what's going on.

**Comment by AbdellahBrache** [comment]
I have downloaded the repo the Brad uploaded to github and I tried to run it in my machine that's where I got the problem the code that I wrote during the course is working good I wanted to use Brad's code for learning reasons

**Comment by bushblade** [comment]
So you downloaded the master branch of this repository?
Then what did you do?
Do you have a database?
Do you have a config/default.json?
How are you running the project?
Do you get any error output in the terminal?

**Comment by AbdellahBrache** [comment]
I have simply cloned the repo in my local machine read the docs and created my mongoDB database I created the default.json file with link to the DB and the github token then I run it with "npm run dev' it lunches the application in port 3000 I go to create a new profiles when I try to save the info I get this error , 
also before I get any thing I get :
"connection <monitor> to 18.185.151.83:27017 closed
[nodemon] app crashed - waiting for file changes before starting..."

![Screenshot from 2020-07-29 12-28-10](https://user-images.githubusercontent.com/45032530/88794906-10c78700-d197-11ea-9240-381214375d80.png)

**Comment by bushblade** [comment]
So from the error output, you're not connected to a database.
So most likely you have your database connection string incorrect or credentials in the string incorrect, or possibly your IP address is not whitelisted for connection to your database.

**Comment by AbdellahBrache** [comment]
Yeah Thank you very much I haven't made the db accessible from everywhere as soon as I changed it it worked perfectly The issue has been resolved thank you very much for your assistance

**Comment by bushblade** [comment]
No problem.
