### ISSUE TITLE
What should be the  code of setAuthToken in utils folder of client,if am using google oauth strategy at backend as there is no token

### ISSUE THREAD

**Issue by TASKMASTER682** [bradtraversy/devconnector_2.0#152]

**Comment by bushblade** [comment]
Hi @TASKMASTER682 
It would be more than just changing the code in utils/setAuthToken.
You would have to follow the [documentation](https://developers.google.com/identity/sign-in/web/sign-in) for that.
As this isn't an issue with the repository code (we don't use google OAuth) then I'll close.
