### ISSUE TITLE
Like & unlike post

### ISSUE THREAD

**Issue by Coddielam** [bradtraversy/devconnector_2.0#155]
Liking and unliking a post is currently handled in two separate routes. I wonder if it actually should be handled in one route for better user experience: 1. find the post, 2. check if it's been liked --> if yes, do a splice to update the post. like, if not, do an unshift. 

Just a thought.

**Comment by bushblade** [comment]
Hi @Coddielam 
I don't see this as improving user experience as the API is abstracted away from the user anyway.
I would argue that from an API standpoint then separate like and unlike routes is a little more declaritive.
I don't think I see this as an issue here with the repository code though, so I'll close.
