### ISSUE TITLE
Illegal arguments: object, string

### ISSUE THREAD

**Issue by georgeraja** [bradtraversy/devconnector_2.0#157]
I`m trying to register login a user after registering it! but it throws this error in the console, please help!

**Comment by bushblade** [comment]
Hi @georgeraja 
Is this an issue with the current repository code or your own project?

**Comment by bushblade** [comment]
Hi again @georgeraja 
I've not heard back from you and can't reproduce this issue with the repository code, so I'll close here as an issue.
If this is a problem you're having with your own code in the course, then please post in the course Q&A and one of us will help you out.
