### ISSUE TITLE
GET http://localhost:3000/api/auth 401 (Unauthorized)

### ISSUE THREAD

**Issue by georgeraja** [bradtraversy/devconnector_2.0#158]
I`m trying to login a user after registering it also throws this error

**Comment by bushblade** [comment]
Hi @georgeraja 
Is this a issue with the current repository code or with your own project?

**Comment by georgeraja** [comment]
@bushblade it`s an issue with my code, I dunno wats a problem, all of my routes working fine with postman, i checked everything again and again but failed to deal with it!

**Comment by bushblade** [comment]
Ah ok.
If it's a problem with your own code you need help with then please post in the Udemy Q&A and one of us will get to you shortly.
If you just need a working project then pleas fork/clone this repository and use that code.
I'll close as an issue here.
