### ISSUE TITLE
BUG: Logout Error !

### ISSUE THREAD

**Issue by JayanthApagundi** [bradtraversy/devconnector_2.0#160]
When I navigate to a particular developer profile/my own profile and click on the logout button, The action logout is being done as it can be known from the redux dev tools, But in the frontend on click on Logout it is leading to Spinner i.e: Loading GIF and going into an infinite state !

**Comment by bushblade** [comment]
@JayanthApagundi is this an issue with the repository code or your own project?

**Comment by JayanthApagundi** [comment]
It's with the repository code and with my own project too.
I m working on my project with this and adding a few features too. 0
