### ISSUE TITLE
PROFILE_ERROR not handled.

### ISSUE THREAD

**Issue by kazuma2448** [bradtraversy/devconnector_2.0#161]
In actions/profile.js the getCurrentUsersProfile() uses PROFILE_ERROR in the catch statement but it is not handled in the auth.js reducer. This lead to a bug where if you navigated to edit-profile while not authenticated, the app would crash saying it cannot read property of null. This is for the original course code branch.

**Comment by bushblade** [comment]
@kazuma2448 can you reproduce this in the master branch code?

**Comment by kazuma2448** [comment]
No, it is just displays the loading spinner. I was finishing up section 9 and it was bothering me that the app was crashing.

**Comment by bushblade** [comment]
I'm afraid the originalcoursecode branch won't get any updates. If you need a working project then use the master branch or if you need help with course code then please post in the course Q&A.
