### ISSUE TITLE
PrivateRoutes are not redirecting to the login page when users are not logged in. It's just showing the spinner component.

### ISSUE THREAD

**Issue by louiejancevski** [bradtraversy/devconnector_2.0#163]

**Comment by bushblade** [comment]
Hi @louiejancevski 
Is this an issue you're experiencing with your own project or with the code from this repository?

**Comment by louiejancevski** [comment]
@bushblade Yes, with both. Since loading is set to true by default, it always loads the spinner component and never gets to <Redirect to="/login" /> when logged out.

In PrivateRoute.js:

`  <Route
    {...rest}
    render={(props) =>
      loading ? (
        <Spinner />
      ) : isAuthenticated ? (
        <Component {...props} />
      ) : (
        <Redirect to="/login" />
      )
    }
  />`

**Comment by louiejancevski** [comment]
@bushblade Yes, with both. Since loading is set to true by default, it always loads the spinner component and never gets to `<Redirect to="/login" />` when logged out.

**Comment by louiejancevski** [comment]
@bushblade Yes, with the code from this repository. Since loading is set to true by default, it always loads the spinner component and never gets to `<Redirect to="/login" />` when logged out.

**Comment by bushblade** [comment]
Hi again.
This sounds like a bug I accidentality introduced in 271b198 
I had one line of code on the wrong line.
It should be fixed in the latest commit so make sure you pull down the latest version.

**Comment by louiejancevski** [comment]
Changing that one line fixed it. Thank you for your help!

**Comment by bushblade** [comment]
No problem.
