### ISSUE TITLE
Issue on deleting an experience 

### ISSUE THREAD

**Issue by abdullahmujahidali** [bradtraversy/devconnector_2.0#164]
Can you help me out I am getting this issue? I am getting this on VS code
![image](https://user-images.githubusercontent.com/48271080/93021218-f9cfdd80-f5fa-11ea-877d-1ddd796b5648.png)
 
and on the chrome dev tool, I am getting this 
![image](https://user-images.githubusercontent.com/48271080/93021244-2126aa80-f5fb-11ea-8880-324f1f32fca2.png)

**Comment by abdullahmujahidali** [comment]
`
router.delete("/education/:edu_id", auth, async (req, res) => {
    try {
        const profile= await Profile.findOne({user: req.user.id});

        // Get remove index  

        const removeIndex= profile.education
        .map(item =>item.id)
        .indexOf(req.params.edu_id);

        profile.education.splice(removeIndex,1);
        await profile.save();

        res.json(profile);

    } catch (err) {
        console.error(err.message);
        res.status(500).send("Server error");
    }
})
`
This is my code of delete an experience in API

**Comment by bushblade** [comment]
Hi @abdullahmujahidali 
From the looks of your output, you don't have a endpoint for `/api/auth` or `/api/profile.experience`
The second url for deleting an experience is obviously wrong.
I'm guessing this is an issue with your own project as I can't reproduce a similar issue using repository code.
If you're a student of Brad's then please post in the course Q&A and one of us will get to your issue.
If you're not a student and just need a working project, then please fork and clone this repository and follow the README on setting up.
I'll close as an issue here as this isn't an issue with repository code.
