### ISSUE TITLE
TypeError: Cannot read property 'isAuthenticated' of undefined

### ISSUE THREAD

**Issue by manish0502** [bradtraversy/devconnector_2.0#166]
×
TypeError: Cannot read property 'isAuthenticated' of undefined
Function.mapStateToProps [as mapToProps]
src/components/auth/Login.js:69
  66 | };
  67 | 
  68 | const mapStateToProps = state => ({
> 69 |   isAuthenticated: state.auth.isAuthenticated
  70 | });
  71 | 
  72 | export default connect(

**Comment by bushblade** [comment]
Hi @manish0502 
Can you explain how you get this issue please so I can try and replicate it?

**Comment by manish0502** [comment]
yes , i am watching 8. React User Authentication , video-3 but when i am adding this "mapStateToProps" to line export default connect(null, { login })(Login) and changing to export default connect(mapStateToProps, { login })(Login) ; i am getting this error : TypeError: Cannot read property 'isAuthenticated' of undefined

**Comment by bushblade** [comment]
Ah ok so you're a student in Brad's MERN course on Udemy?
And this isn't an issue with the repository code?
If you post a in the course Q&A with a link to your repository and a clear explanation of the issue you're facing then one of us will help you out.
I'll close as an issue here on GitHub.
