### ISSUE TITLE
Edit profile not updating social input changes

### ISSUE THREAD

**Issue by vraxzeztan** [bradtraversy/devconnector_2.0#167]
On clicking submit on edit profile, it does not update the state if only changes are made in social inputs.

**Comment by bushblade** [comment]
Hi @vraxzeztan 
I just tried to replicate your issue but I cannot.
Can you make sure your code is up to date with the repository?

**Comment by vraxzeztan** [comment]
Hi @bushblade , I got my error rectified by changing EditProfile and CreateProfile into ProfileForm .
