### ISSUE TITLE
dependencies are broken

### ISSUE THREAD

**Issue by the-mec** [bradtraversy/devconnector_2.0#171]
over 3000+ client dependencies are broken  or deprecated when you do npm install.

**Comment by bushblade** [comment]
Hi @the-mec 
Yeah that's pretty normal for installing a react app.
You can run `npm audit fix` which would resolve most of them
Or you can run `npm audit` to find out more about them and if they are likely to be an issue for you.
As of testing myself today `npm audit fix` resolves all of them.
