### ISSUE TITLE
When Routing files using Express, module not found is shown as error

### ISSUE THREAD

**Issue by vamsin07** [bradtraversy/devconnector_2.0#173]
Changed the routing to get things done

// Define Routes
app.use('/api/user', require('./config/routes/api/user'));
app.use('/api/auth', require('./config/routes/api/auth'));
app.use('/api/profile', require('./config/routes/api/profile'));
app.use('/api/posts', require('./config/routes/api/posts'));

**Comment by bushblade** [comment]
Hi @vamsin07 
I'm not sure I understand what the issue you're raising actually is.
As of testing today I can successfully run the project in development and production with no such error.
Can you explain more about the issue you're raising please?

**Comment by vamsin07** [comment]
So i was just following what Mr Brad taught us on the tutorial titled "Route Files With Express Router" where the code which I shared above were the changes which ran successfully.

P.S- I am not facing an issue, I just raised this because initially with Mr. Brad's approach I was not able to see the Api calling in Postman, however after making these changes I was able to

**Comment by bushblade** [comment]
Ah Ok so this is a problem you're having as you code along in the Udemy course? And not an issue with the repository code?
If you post a question in the course Q&A, one of us will be along to answer your question there.
I'll close as an issue.
