### ISSUE TITLE
My gravatar still not showing. may I confirm if this email that i'm using in Github that I use as login on my devconnector app should show as my avatar right?

### ISSUE THREAD

**Issue by KeithRussel** [bradtraversy/devconnector_2.0#174]
https://github.com/bradtraversy/devconnector_2.0/blob/0b08fd722260fcd2cb8957c4682e941afee9e721/routes/api/users.js#L44

**Comment by bushblade** [comment]
Hi @KeithRussel

No Gravatar is in no way linked to GitHub.
The users email needs a Gravatar registered at gravatar.com

**Comment by KeithRussel** [comment]
Yeah, solved thanks
