### ISSUE TITLE
Like and Dislike button not updating in realtime, I always need to refresh my browser to see the update result.

### ISSUE THREAD

**Issue by KeithRussel** [bradtraversy/devconnector_2.0#175]
![asd](https://user-images.githubusercontent.com/14196374/96098156-6133c280-0f04-11eb-81f0-0415a583363e.png)
as you can see the number of like didn't change when I clicked. It should update to 3 without any refresh.

**Comment by KeithRussel** [comment]
Fixed. I just restarted my terminal and run npm run dev again.

**Comment by mfaisalakram** [comment]
I am also facing same problem, if you have resolved the issue then please share with me..
