### ISSUE TITLE
TypeError: name is undefined in both ProfileTop.js and ProfileAbout.js

### ISSUE THREAD

**Issue by tydangelo18** [bradtraversy/devconnector_2.0#177]
It says name is undefined. I'm not sure if it has something to do with how I de structured it or not? 

![Screen Shot 2020-11-16 at 4 46 55 PM](https://user-images.githubusercontent.com/60044459/99317271-664d9f80-282b-11eb-8f27-2ccaba3958b0.png)
![Screen Shot 2020-11-16 at 4 47 12 PM](https://user-images.githubusercontent.com/60044459/99317274-66e63600-282b-11eb-8221-2c898938c530.png)

**Comment by bushblade** [comment]
Hi @tydangelo18 
Is this an issue with your own project or with code in the repository?
