### ISSUE TITLE
react app can't compile when axios is removed front client side package.json

### ISSUE THREAD

**Issue by aaronvonkreisler** [bradtraversy/devconnector_2.0#178]
There seems to be an issue with Create React App compiling when axios was removed from client and added to the server dependencies only. However, when axios is reinstalled in both client-side and server-side package.json it works just fine. Is this a known issue? Also, is having axios as a dependency in both  client and server going to cause any issues?

**Comment by aaronvonkreisler** [comment]
Here is the error message:

```
[1] Failed to compile.
[1]
[1] ./src/utils/api.js
[1] Cannot find file: 'index.js' does not match the corresponding name on disk: 'C:\Users\Aaron von Kreisler\desktop\dev-connector\node_modules\axios\Desktop'.
```

**Comment by bushblade** [comment]
Hi @aaronvonkreisler 
You may need to generate new lock files.
So delete the node_modules in both root and client and delete the package-lock.json in both root and client the run `npm i` in both client and root and see how that goes.
