### ISSUE TITLE
/api/profiles breaks

### ISSUE THREAD

**Issue by hemantsaini-7** [bradtraversy/devconnector_2.0#180]
The project breaks when a user deletes his account and tries to go on Developers Tab (GET /api/profiles).

ERROR : statusText & resposne undefined.

**Comment by bushblade** [comment]
Hi @hemantsaini-7 
I cannot reproduce the same issue testing using the repository code.
Can you please make sure you are using the latest code in the repository.

**Comment by hemantsaini-7** [comment]
> Hi @hemantsaini-7
> I cannot reproduce the same issue testing using the repository code.
> Can you please make sure you are using the latest code in the repository.

Mate can you tell me the process, like after cloning this repo, what steps you take next coz that error comes for me!

**Comment by bushblade** [comment]
Did you read through the read me and create a default.json with your credentials and database connection?

**Comment by hemantsaini-7** [comment]
> Did you read through the read me and create a default.json with your credentials and database connection?

I have created this project on my own..!
So, everything is fine just that break occurs, I guess I have to check the route again!
Thanks, bushblade!

**Comment by bushblade** [comment]
Ah so this isn't an issue with the repo code?
If you're a student of Brad's then post in the course Q&A and one of us will be along to help you out.
