### ISSUE TITLE
Dependency cycle

### ISSUE THREAD

**Issue by denisRajlic** [bradtraversy/devconnector_2.0#187]
In your updated version, you created a utils/api.js file alongside a setAuthToken.js file. Es-lint, throws an dependency cycle error, since the api module imports store.js and store.js imports setAuthToken. 

I was wondering if this is ok to ignore, or should it be updated? I believe the problem goes away if you declare api and setAuthToken directly in store.js, but then you lose modularity i guess. Any ideas?

**Comment by bushblade** [comment]
Hi @denisRajlic 
Thanks for the heads up, what's the warning you're seeing?
I'm guessing this is only showing up on more recent versions of create-react-app as it's not showing up for me on cloning the repository code. I am aware a lot of the es lint rules got overhauled recently, so if you're using newer version of react then I expect the newer rules are flagging this.
I would say it's safe to suppress the warning, but the linter usually is a pretty good indicator that we can improve something, so I'll look into it further.

**Comment by denisRajlic** [comment]
The ES-Lint error is: import/no-cycle. I'm definitely using a newer version of eslint, since i followed along and didn't clone the repo. 
Do you think pasting the api and setAuthToken modules directly into store.js would be a bad idea / bad coding practice?

**Comment by bushblade** [comment]
Hi again.
I just updated all packages locally and I'm not seeing the same linting error.
My current local branch client/package.json is
```json
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.1",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "uuid": "^8.3.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "proxy": "http://localhost:5000"
}
```
> Do you think pasting the api and setAuthToken modules directly into store.js would be a bad idea / bad coding practice?
I wouldn't, I think that could get confusing and I'm not seeing any linting warning personally.
Can you double check your code is the same as the repo code?

**Comment by bushblade** [comment]
I am seeing the other linting errors regarding 

`Unexpected default export of anonymous function  import/no-anonymous-default-export`

but no dependency cycle warnings.

**Comment by denisRajlic** [comment]
Yes, I cloned the repo and I get the same error as before. But I believe I know where the problem is. In the home directory (outside client/) I have these dev dependencies. These were installed automatically with npm i eslint, but the important one is eslint-plugin-import. Do you have this plugin installed? Without it, the error won't show I believe.

```json
 "devDependencies": {
    "concurrently": "^5.1.0",
    "eslint": "^7.16.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "nodemon": "^2.0.2"
  }
```

**Comment by bushblade** [comment]
Ah right yeah that would be it in your case. If you're using your own es lint set up then I'll close the issue, as this isn't an issue with course code or repository code.
