### ISSUE TITLE
Create and Update Profile Route

### ISSUE THREAD

**Issue by ShashankAgarwal77** [bradtraversy/devconnector_2.0#191]
I was attending the lecture where we create POST API for profile and created Build Profile Object and Build Social Object and update them with Profile Module.

In Postman Request if I give this body data
{
    "company" : "Freelancer",
    "status" : "Developer",
    "website" : "http://shashankagarwal.netlify.app",
    "skills" : "HTML, CSS, JS, C++",
    "location" : "India",
    "bio": "Full Stack Digital Designer and Developer",
    "githubusername" : "ShashankAgarwal77",
    "twitter" : "https://twitter.com/_iamtheshashank/",
    "instagram" : "https://www.instagram.com/_iamtheshashank/",
    "linkedin" : "https://www.linkedin.com/in/shashank-agarwal11/"
}

I am receiving this,
{
    "social": {
        "twitter": "https://twitter.com/_iamtheshashank/",
        "linkedin": "https://www.linkedin.com/in/shashank-agarwal11/",
        "instagram": "https://www.instagram.com/_iamtheshashank/"
    },
    "skills": [
        "HTML",
        "CSS",
        "JS",
        "C++"
    ],
    "_id": "5feaff4846138d1a3aae8e15",
    "user": "5fe426f740ce9832afd0039d",
    "company": "ShashankAgarwal77",
    "experience": [],
    "education": [],
    "date": "2020-12-29T10:04:56.081Z",
    "__v": 0
}

Here is the profile.js from routes/api
[profile.js.zip](https://github.com/bradtraversy/devconnector_2.0/files/5750404/profile.js.zip)

**Comment by bushblade** [comment]
Hi @ShashankAgarwal77 
Is this an issue you're facing with your own project or with a clone of the repository code?
If it's your own code and you're a student of Brad's then please post in the course Q&A and one of us will be along to help you.
If it's an issue with the repository code then please make sure you are using the latest code in the master branch of this repository.

**Comment by kirasiris** [comment]
You can PM so I can help you but by just looking at your code I think you need to double check your if-statements.....

my email: kebin1421@hotmail.com

**Comment by bushblade** [comment]
Closing due to lack of information and stale issue.
