### ISSUE TITLE
Missing info in the readme project updates? - "Log out user on token expiration"

### ISSUE THREAD

**Issue by oddgrd** [bradtraversy/devconnector_2.0#202]
In the section "Log out user on token expiration", quite a few changes are made and there are links to the affected files. However, not all affected files are linked to in the readme. As I tried to implement these changes, my authorization broke: I was logged out immediately after logging in. After checking the linked affected files thoroughly, I fond no solution. Then I checked the setAuthToken.js in utils, and realized it too needed to be changed from axios to ./api. This fixed my issue. Should this be mentioned in the the readme? 

This is my first github issue submission, so I apologize in advance if I am mistaken in posting this here, or if am I not following proper issue etiquette.

Thanks for the great course, I learned a lot!

**Comment by bushblade** [comment]
Hi @oddgrd 
Thanks for the issue, that's a great point. I'll be sure to make it clearer in the README

**Comment by bushblade** [comment]
fixed in c1bb54c
