### ISSUE TITLE
Actions using outdated types

### ISSUE THREAD

**Issue by desouzapreston** [bradtraversy/devconnector_2.0#206]
So I haven't gotten a bug but I did notice that in src>actions>auth.js under Register user there is 
`dispatch({
            type: REGISTER_FAIL
        })`
is called. Will this impact the application performance in any smaller way? _**Is this line removable?**_
In the reducers in the latest file structure register_fail and login_fail have been removed in place of logout and auth_error functionality.

Same goes for login, thank you in advance!

**Comment by desouzapreston** [comment]
It's also in the src>actions>types in case we can remove it, it should be removed from both instances

**Comment by bushblade** [comment]
Hi @desouzapreston 
Although there is no longer a case for REGISTER_FAIL in the reducers, it is still useful to see this case in the dev tools.
