### ISSUE TITLE
Token lost everytime refresh the page

### ISSUE THREAD

**Issue by johnnychang25678** [bradtraversy/devconnector_2.0#209]
Hi,

I just found the bug recently. When browser refresh the page, the token would be lost therefore user will be logged out. Not sure where the bug is.

**Comment by bushblade** [comment]
Hi @johnnychang25678 
I can't reproduce that using the current code from this repo, can you make sure you are using the latest code?

**Comment by bushblade** [comment]
Closing due to lack of information and stale issue.
