### ISSUE TITLE
production.json

### ISSUE THREAD

**Issue by ismailalabou** [bradtraversy/devconnector_2.0#210]
> what should contains config/production.json file ?
@bradtraversy

**Comment by ismailalabou** [comment]
is it just a clone of default.json

**Comment by bushblade** [comment]
Hi @ismailalabou 
It should be the same as what you have in your default.json
You can use different credentials and database for production and development
As this isn't an issue I'll close.

**Comment by ismailalabou** [comment]
hello @bushblade thank you!
