### ISSUE TITLE
setAlert is not a function

### ISSUE THREAD

**Issue by ayaanmondal** [bradtraversy/devconnector_2.0#211]
https://github.com/ayaanmondal/BUIE_ConnectedWeb_v2/issues/1

I am learning from your project, but I am getting an error setAlert is not a function, in register.js file,
please tell me how can I solve this ???

**Comment by kirasiris** [comment]
Did you pass it as a prop?; did you declare it as required in the propTypes(all the way to the end of the file)?; did you connect it to the store using `connect(mapStateToProps, {setAlert})`?

**Comment by ayaanmondal** [comment]
![Screenshot from 2021-04-09 10-26-18](https://user-images.githubusercontent.com/46599244/114130552-753e0700-991e-11eb-9c7e-df8273353e70.png)

Please go through my files 
https://github.com/ayaanmondal/BUIE_ConnectedWeb_v2/tree/master/client/src

**Comment by kirasiris** [comment]
Well, two things are making me wonder about your code:

- Why are you exporting your Register constant twice?
--  You have `export const Register = ({ setAlert }) => {....}`
--  `export default connect(null, { setAlert })(Register);`
- Secondly, you're calling the function but you  don't have your `<Alert />` component available to be fired whenever said request is done.

At the moment, the only thing I see wrong(i checked your action and reducer), Is the exporting of the same constant, that might be causing the problem?. Not having you Alert component should not be throwing any error..

**Comment by ayaanmondal** [comment]
Still not able to solve, please give a PR

**Comment by ayaanmondal** [comment]
![Screenshot from 2021-04-10 20-30-55](https://user-images.githubusercontent.com/46599244/114274375-baa42680-9a3b-11eb-9393-d569303bfa43.png)

**Comment by kirasiris** [comment]
You got it right the first time. Tbh, I don't know why you're receiving the setAlert is not a function error.

The errors that you have now are because you probably removed the setAlert prop by accident (you already had it); that's the error of "setAlert marked as required?"

The other ones are easy to spot and fix, you need to fix the html element in which you have `class` instead of `className`.

I checked your reducer yesterday and did not see any error, unless you have forgotten to include it in your combineReducers

**Comment by kirasiris** [comment]
I just noticed something in your reducer, I think you're supposed to import it the same way you name it. The reducer has the line of `export default alertReducer` and your combine reducers is importing it as `alert`

**Comment by ayaanmondal** [comment]
Changes done still getting the error now for register prop also.

**Comment by kirasiris** [comment]
You still need to change your `class` to `className`.

For the register prop; can you try this?: `connect(null, { setAlert, register })(Register);`

**Comment by kirasiris** [comment]
How are you importing your Register component in your routing file? `import { register } from '.....yada/yada/Register'?

**Comment by bushblade** [comment]
I'll close this as an issue as it's not an issue with the repo code.

**Comment by ayaanmondal** [comment]
> How are you importing your Register component in your routing file? `import { register } from '.....yada/yada/Register'?

can't understand !

**Comment by ayaanmondal** [comment]
> You still need to change your `class` to `className`.
> 
> For the register prop; can you try this?: `connect(null, { setAlert, register })(Register);`

Changed class to className but still getting the error
