### ISSUE TITLE
probléme avec le code message d 'erreur   Proxy error: Could not proxy request /api/auth from localhost:3000 to http://localhost:5000/. See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).  Proxy error: Could not proxy request /api/users from localhost:3000 to http://localhost:5000/. See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

### ISSUE THREAD

**Issue by pascalsarr** [bradtraversy/devconnector_2.0#212]
Bonjour j'aimerais savoir ki a reussi a éxécuter le code en le téléchargeant sans pour autant le reprendre carrément a zéro.

**Comment by bushblade** [comment]
Hi @pascalsarr 
So you just want to clone or download the repository and run the project?
Please make sure to have a read through the README, as instructions are there.

**Comment by pascalsarr** [comment]
Salut @bushblade  j ai tout suivi a la lettre le readme mon souci c ca 
![Capture](https://user-images.githubusercontent.com/39752128/114164741-2e9add80-991b-11eb-994f-d4cf75bc7000.PNG)

**Comment by bushblade** [comment]
Hi again.
Are you using the latest code from the master branch?
If so you shouldn't see such warnings.
For your Proxy error, that sounds like your API server is not running.
Please make sure to read through the README if you are just wanting to clone the repository and run it .

**Comment by pascalsarr** [comment]
bushblade Merci bcp je vous remercie du fond du coeur c' est réglé

**Comment by bushblade** [comment]
No problem.
