### ISSUE TITLE
Cannot log in user

### ISSUE THREAD

**Issue by DeeIdowu** [bradtraversy/devconnector_2.0#22]
For some odd reason on the back-end I cannot log in, registration is fine. Ive changed the value of the x-auth-token as well. It user registered is stores upon MongoDB atlas. Ive checked the package.json to see if Bcrypt it working as well.
Below are screenshots of the errors I'm receiving as well as my code, seeking assistance to get this web application fully functioning. Please and thank you.
![Screen Shot 2019-06-24 at 3 44 57 PM](https://user-images.githubusercontent.com/38046425/60047422-b4db2680-9697-11e9-8116-d04f64e730c4.png)
![Screen Shot 2019-06-24 at 3 45 31 PM](https://user-images.githubusercontent.com/38046425/60047425-b6a4ea00-9697-11e9-905b-8ebd9835fa26.png)
![Screen Shot 2019-06-24 at 3 47 29 PM](https://user-images.githubusercontent.com/38046425/60047430-bad10780-9697-11e9-9eee-a1c89943eae9.png)
![Screen Shot 2019-06-24 at 3 49 10 PM](https://user-images.githubusercontent.com/38046425/60047431-bad10780-9697-11e9-95d2-4a966df064e2.png)
![Screen Shot 2019-06-24 at 3 49 19 PM](https://user-images.githubusercontent.com/38046425/60047432-bad10780-9697-11e9-8f8d-cca7fd8f19e6.png)

**Comment by dylanprem** [comment]
It looks like you didn't install bcryptjs as a dependancy. npm i --save bcryptjs.

**Comment by bushblade** [comment]
As this has had no response for 6 months and doesn't appear to be an issue with the repo code, I'm closing this issue.
