### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by TravisSomaroo** [bradtraversy/devconnector_2.0#232]
Get an error on CSV, "Cannot read property 'filter' of undefined", when running the like a post PUT request on Postman API.

// @route   PUT api/posts/like/:id
// @desc    Like a post
// @access  Private

router.put('/like/:id', auth, async (req, res) => {
	try {
		const post = await Post.findById(req.params.id);

		//Check if the post has already been liked
		if (
			post.likes.filter((like) => like.user.toString() === req.user.id).length >
			0
		) {
			return res.status(400).json({ msg: 'Post already liked' });
		}

		post.likes.unshift({ user: req.user.id });

		await post.save();
		res.json(post.likes);
	} catch (err) {
		console.error(err.message);
		res.status(500).send('Server Error');
	}
});

module.exports = router;

**Comment by bushblade** [comment]
Hi @TravisSomaroo that would say to me that your Post has no likes ie. `post.likes` is undefined, so likely an error in the Schema creation as Post.likes should default to an empty array.
Check in your database that your Post has a likes property on it.

**Comment by bushblade** [comment]
I would also suggest that using Array.some would be more appropriate than Array.filter and checking the length.
```js
    // Check if the post has already been liked
    if (post.likes.some((like) => like.user.toString() === req.user.id)) {
      return res.status(400).json({ msg: 'Post already liked' });
    }

    post.likes.unshift({ user: req.user.id });

    await post.save();
```

**Comment by bushblade** [comment]
Closing due to lack of information and suspected students code, not an issue with repo.
