### ISSUE TITLE
TypeError: Cannot read property '_id' of null in ProfileItem.js

### ISSUE THREAD

**Issue by Birdperson9** [bradtraversy/devconnector_2.0#234]
Downloaded project from Github,
Added a default.json,
Installed server dependencies,
Installed client dependencies,
Ran npm run dev.
Everything works great except Developers page. Can't get all profiles, it says TypeError: Cannot read property '_id' of null in ProfileItem.js. Single Profile page works fine.

**Comment by bushblade** [comment]
Hi @Birdperson9
That sounds like you may have corrupt data in your database.

**Comment by Birdperson9** [comment]
Нou are absolutely right! Thanks, you are doing great things :)
