### ISSUE TITLE
Unable to launch application in Heroku

### ISSUE THREAD

**Issue by prabhupadswain** [bradtraversy/devconnector_2.0#235]
When I am deploying in heroku, the build succeeds but the application gives an error while launching. When, i run the command the heroku logs --tail in the terminal ,

the following warnings comes :

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.       
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/app/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.

and some errors come which are as follows : 

/app/node_modules/config/lib/config.js:182
 throw new Error('Configuration property "' + property + '" is not defined');

Error: Configuration property "mongoURI" is not defined

at=error code=H10 desc="App crashed" method=GET path="/" host=arcane-brushlands-34985.herokuapp.com request_id=b192e464-4c9f-4429-987c-11f88352064b fwd="157.41.64.115" dyno= connect= service= status=503 bytes= protocol=https

at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=arcane-brushlands-34985.herokuapp.com request_id=fe30d46d-2cf3-4d63-a170-66c1fcdc60ff fwd="157.41.64.115" dyno= connect= service= status=503 bytes= protocol=https

**Comment by bushblade** [comment]
Hi @prabhupadswain 
The error output says that you didn't add a config/production.json file.
Since this isn't an issue with the repo code, I'll close.

**Comment by prabhupadswain** [comment]
> Hi @prabhupadswain
> The error output says that you didn't add a config/production.json file.
> Since this isn't an issue with the repo code, I'll close.



> Hi @prabhupadswain
> The error output says that you didn't add a config/production.json file.
> Since this isn't an issue with the repo code, I'll close.

Thank you @bushblade . It worked for me now.
