### ISSUE TITLE
profile.experience.unshift is not a function

### ISSUE THREAD

**Issue by hassan-turi** [bradtraversy/devconnector_2.0#236]
I am working on the course and I reached the place where we are adding experience endpoint
try {
      const profile = await Profile.findOne({ user: req.user.id });

      profile.experience.unshift(exp); // here we get error it says unshift is not a function

      await profile.save();

      res.json(profile);

**Comment by bushblade** [comment]
Hi @hassan-turi 
That says to me that `profile.experience.unshift` is most likely undefined, which probably means that `profile.experience` is an object and not an array.
That's my guess anyway but no one can know for certain without seeing your code.
If you are following along with the Udemy course, then please post in the course Q&A and one of us will be able to help you.
Make sure to provide a link to your project's repository.
I'll close here as an issue as it's not an issue in the repository code.
