### ISSUE TITLE
TypeError: Cannot read property 'company' of null --> EditProfile.js file

### ISSUE THREAD

**Issue by KetulParikh** [bradtraversy/devconnector_2.0#25]
Hi my useEffect is not working when the loading flag is changing. I got this error

TypeError: Cannot read property 'company' of null

When component mounted value of profile was null. then useEffect ran stil state is not affected and setFormData gives the above error.

**Comment by emily6699** [comment]
Hello, I have the same issue too. How to solve it? Thank you

**Comment by KetulParikh** [comment]
@emily6699 I have solved the issue. The problem was useEffect was using ```loading``` variable as dependencies. When I check my reducer file there was a typo mistake. I accidentally wrote ```laoding``` instead of  ```loading```. So the useEffect was not running again with the change of  ```laoding``` as it depends on ```loading```.

I recommend you to check all typos and state variables. The error occurs because after changing the value of dependencies (in this case ```loading```) the useEffect is not running again.

**Comment by sandtr0ut** [comment]
I have the same error.  I've quadruple-checked for any typos or errors with my state variables but, the error persists.  It's something with the [loading] or [loading, getCurrentProfile] (the latter is what Brad has in the repo) in the useEffect (line 48-ish in components/profile-forms/EditProfile.js).

I have re-watched video #49 many, many times over and have been banging at this for six hours now.  Confounding, I must say.

**Comment by sandtr0ut** [comment]
For me the culprit seems to have been ESLint.  It kept changing the `[loading]` inside `useEffect` to include the so-called 'missing dependencies'.  I added `// eslint-disable-next-line react-hooks/exhaustive-deps` immediately above the loading variable, which was on line 48 for me.  The problem persisted until I exited the server, cleared my browser cache, and reloaded everything.  Works now.

**Comment by emily6699** [comment]
Cool. thank you @KetulParikh and @sandtr0ut !

**Comment by bushblade** [comment]
As this has had no response for 6 months and doesn't appear to be an issue with the repo code, I'm closing this issue.
