### ISSUE TITLE
my Like button is not updating on runtime. ( while updating on reload page or window and mu unlike button working properly ).

### ISSUE THREAD

**Issue by mfaisalakram** [bradtraversy/devconnector_2.0#255]

**Comment by bushblade** [comment]
Hi @mfaisalakram 
Can you just confirm that you are using the latest code from the repository and let me know the steps to reproduce the issue please?

**Comment by mfaisalakram** [comment]
Mr @bushblade

**Comment by bushblade** [comment]
Hi again @mfaisalakram 
If this is not a problem you are experiencing with the repository code then I'll close here as an issue.
If this is something you are experiencing while following the Udemy course, then please post in the course Q&A and one of us will help you out.
Make sure to include 
 * Clear steps to reproduce the issue
 * What you have done so far to fix the issue
 * Any error output you see in your console or terminal
 * A link to your project's repository so we can see all your code
