### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by Akbar4242** [bradtraversy/devconnector_2.0#257]
Could not proxy request /api/profile/me from localhost:3000 to http://localhost:5000/.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED). I cant solve this please help me!

**Comment by bushblade** [comment]
Hi @Akbar4242 
That sounds like your API server is not running?
This doesn't appear to be an issue with the repository code that I can reproduce. Can you confirm that you are using the latest code from the master branch and let us know how you are running the project?
If you are a student of Brad's then please post a question in the course Q&A and one of us will be along to help you.

**Comment by ngc7023** [comment]
I solved this problem by change the package.json by adding '--ignore client', but I don't know why it works.

 "scripts": {
    "start": "node server",
    "server": "nodemon server --ignore client",
    "client": "npm start --prefix client",
    "dev":"concurrently \"npm run server\" \"npm run client\""
  }
