### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by emily6699** [bradtraversy/devconnector_2.0#26]
After deployed to Heroku successfully, my website says "Invalid Host header", can anyone help? Thank you

**Comment by Omar-Handouk** [comment]
Uhmmmm, a little more details please.
Like Heroku's Stacktrace, any admin process logs, steps to reproduce, heroku commands you typed, ..etc

**Comment by bushblade** [comment]
As this has had no response for 6 months, lack of actionable information and doesn't appear to be an issue with the repo code, I'm closing this issue.
