### ISSUE TITLE
Proxy error: Could not proxy request

### ISSUE THREAD

**Issue by GotteNaresh** [bradtraversy/devconnector_2.0#263]
Proxy error: Could not proxy request /api/users from localhost:3000 to http://localhost:5000/ (ECONNREFUSED).[](url)
![proxyerror](https://user-images.githubusercontent.com/14179583/144594822-6c1fc0cc-ed77-4898-aea1-e57bb126fbbe.PNG)

could you please help me on it how to fix this issue?

**Comment by bushblade** [comment]
Hi @GotteNaresh 
That says to me that either your API server is not running or is not responding to requests made to /api/users.
Can you confirm?

**Comment by Mozler** [comment]
Make sure you have added backslash as last character while setting up proxy option on package.json file. (under client folder)
Instead of this:
`"proxy": "http://localhost:5000"`
Should be like this:
`"proxy": "http://localhost:5000/"`

**Comment by bushblade** [comment]
As we have not heard back from @GotteNaresh and this doesn't seem to be an issue with repository code I'll close here.
