### ISSUE TITLE
Chapter based commits

### ISSUE THREAD

**Issue by armaneshaghi** [bradtraversy/devconnector_2.0#265]
Hi Brad, Is there a way for me to get the repo at specific commits based on your Udemy videos? Say, to progress lesson by lesson?

**Comment by bushblade** [comment]
Hi @armaneshaghi 
Not per lesson really but if you go to the [origionalcoursecode](https://github.com/bradtraversy/devconnector_2.0/tree/originalcoursecode) branch and view the [older commits](https://github.com/bradtraversy/devconnector_2.0/commits/originalcoursecode?after=7e79a4247f4ee676e984a2a81be5c92de96fc2c8+104&branch=originalcoursecode) there, you can get a rough approximation of what happened per lesson.
Hope that helps.
