### ISSUE TITLE
Navbar covers other components

### ISSUE THREAD

**Issue by ngc7023** [bradtraversy/devconnector_2.0#266]
Why navbar covers other components?

![image](https://user-images.githubusercontent.com/51163198/147841833-023f5c04-84cd-4df1-8f2c-8055f3ac2d5c.png)

I used the App.css in https://github.com/bradtraversy/devconnector_2.0/blob/master/client/src/App.css

App.js
![image](https://user-images.githubusercontent.com/51163198/147841859-61c810e5-437c-439f-aa62-f3307f5648ca.png)

Dashboard.js
![image](https://user-images.githubusercontent.com/51163198/147841863-fa9519cc-9390-47f6-b45f-a1515e27320c.png)

**Comment by bushblade** [comment]
Hi @ngc7023 
Thanks for the issue.
Are you using the latest code in the repository?
I don't see the same issue as you in my clone of the repo code.

**Comment by ngc7023** [comment]
@bushblade Thank you for the reply. I solved this problem by replace <Fragment> with <section className='container'>!
