### ISSUE TITLE
I can't run the backend cause of "app crashed"

### ISSUE THREAD

**Issue by GlistenSTAR** [bradtraversy/devconnector_2.0#267]
Hi, how are you? I saw your devconnecter project and I want to run the project on my local. so I installed all modules and try to run the server.
But when I run the backend server, It shows errors "app crashed-waiting for file changes before stating....."
What kind of this errors and how can I fix this. I add the image. Please kind check and let me know what is the solution.
Thanks in advance.
![image](https://user-images.githubusercontent.com/75786284/157279755-e25f3f39-fb45-4632-8ead-e0997f64efbe.png)

P.S. I didn't changed any code and It cloned new project from this repo.

**Comment by bushblade** [comment]
Hi @GlistenSTAR 
The error says your MongoDB connections string is invalid, perhaps it is undefined?
Did you read the project README and add your own config/default.json with DB connection string to connect to your database?

**Comment by bushblade** [comment]
[Please read this part of the README](https://github.com/bradtraversy/devconnector_2.0#add-a-defaultjson-file-in-config-folder-with-the-following)

**Comment by GlistenSTAR** [comment]
hmmm...
I tried step following readme file. So mongodb is running now.
![image](https://user-images.githubusercontent.com/75786284/157283030-c377287a-c7bc-4975-b0e2-57230482db19.png)
![image](https://user-images.githubusercontent.com/75786284/157283140-3057c8d5-8d54-4a9c-ae27-0ae62a49f5a1.png)

What is wrong on here?

**Comment by bushblade** [comment]
That looks correct to me if you are running your DB locally and can connect to it.
Do you still see the same error in your terminal?
Note that if you have just added your config file, you will need to restart the server to pick up the config file.

**Comment by GlistenSTAR** [comment]
yes, I rerun the server. but It shows same result. 

![image](https://user-images.githubusercontent.com/75786284/157284482-5cc17831-0172-4de4-9848-0503cbff6144.png)

**Comment by GlistenSTAR** [comment]
is it not working on local? When I try with online MongoDB server, It's running now...
hmmm...

**Comment by bushblade** [comment]
Most likely the issue is with how localhost resolves on your system.
Check your hosts file or try connecting to 127.0.0.1

**Comment by GlistenSTAR** [comment]
Okay, really thanks for your effort. :) 👍🏻
