### ISSUE TITLE
/api/profile/me returns 400 after registration

### ISSUE THREAD

**Issue by kamil-zielinski** [bradtraversy/devconnector_2.0#27]
I've just cloned repo, set mongodb uri, run both `npm i` and wanted to test your app. I registered without problems and got redirected to Dashboard with 'Create Profile' button. When I click it I get 400 from `/api/profile/me` with a response `{"msg":"There is no profile for this user"}`.

**Comment by perkov22** [comment]
Same problem I have.

**Comment by perkov22** [comment]
But when i go to developers and click some profile and then dasboard it shows me create-profile...

**Comment by kirasiris** [comment]
The message is clear. You register as a user, then you will have to create a profile for said user by going to the dashboard and clicking into the Create Profile button.

Have you guys bought his course in Udemy?. Brad pretty much explains it all.

**Comment by perkov22** [comment]
I know. But when i click create user it wont take me there. I got redirect to dashboard.

**Comment by kamil-zielinski** [comment]
@kirasiris 

> then you will have to create a profile for said user by going to the dashboard and clicking into the Create Profile button
Ant this is what throws error

**Comment by kedus1234** [comment]
here same error.. how to fix it?

**Comment by bushblade** [comment]
As this has had no response for 6 months, lack of actionable information and doesn't appear to be an issue with the repo code, I'm closing this issue.
