### ISSUE TITLE
Question regarding the updated version of the github code in api/profile.js

### ISSUE THREAD

**Issue by rohanrkamath** [bradtraversy/devconnector_2.0#270]
Hi! 

So I have been following the course and has been really informative, although challenging.

I noticed that the code explained by Brad in the course has been updated here, and I have a question pertaining to this line -https://github.com/bradtraversy/devconnector_2.0/blob/4be414c6a54994c18397dba9c927ad67b878508b/routes/api/profile.js#L334

My question is, what does the GitHub token imply? In the course, while making the o-auth app, there was a client_id and secret that was to be added in the default.json. So the GithubToken corresponds to which of these? The client_id or secret? 

I used both of them as tokens, and it gave me a `Request failed with status code 401` in the console.

Thanks!

**Comment by bushblade** [comment]
Hi @rohanrkamath 

> So the GithubToken corresponds to which of these? The client_id or secret?

Neither.
Please have a read of the [notes in the README](https://github.com/bradtraversy/devconnector_2.0#changes-to-github-api-authentication) about this.

**Comment by rohanrkamath** [comment]
Oh, the Github token! Got it. 
But then what's the point of even creating the o-auth app? Is it no longer required? As the client_id and secret don't seem to be required in the code anymore...

**Comment by bushblade** [comment]
Hi again.
There is no point. Authentication to the GitHub API has changed since the course was recorded.
