### ISSUE TITLE
Not able to login or register after deploying to heroku

### ISSUE THREAD

**Issue by GeekyGoyal** [bradtraversy/devconnector_2.0#275]
Attaching the screenshots. Kindly help.

![Screenshot (651)](https://user-images.githubusercontent.com/75560383/190705927-d176f331-96e7-4bb8-bdb9-d87115186c51.png)
![Screenshot (652)](https://user-images.githubusercontent.com/75560383/190705938-5b8e323b-f79c-434d-b019-7f78a8cf6d59.png)
![Screenshot (653)](https://user-images.githubusercontent.com/75560383/190705943-29030599-c8d1-405e-ba93-5f8f1f563b89.png)

**Comment by bushblade** [comment]
Hi @GeekyGoyal 
Do you get this issue with your own code and are you a student of the Udemy course?
Or do you get this issue with a clone of the repository code?
Have you inspected the request/response in your developer tools network tab? Was the x-auth-token header added?

**Comment by GeekyGoyal** [comment]
Hey @bushblade
I'm a student of the udemy course. Though I've added a few more features to it and made some changes in the front-end part.
You can refer to the code here --> [Repo Link](https://github.com/GeekyGoyal/CampusConnect)

**Comment by bushblade** [comment]
If you post in the course q&a I can help you out there.
