### ISSUE TITLE
Trying to add experience and education in put request showing error

### ISSUE THREAD

**Issue by abhijeetraut456** [bradtraversy/devconnector_2.0#278]
This error occurred from Profile Schema and profile router  I don't know why please check . Even your code copy and past nothing work...
 
profile validation failed: experience.0.from: Cast to date failed for value "19-09-1999" (type string) at path "from", status: Path `status` is required.

**Comment by bushblade** [comment]
Hi @abhijeetraut456 
This isn't a problem with the code, it's a problem with the request you are making.
The Schema is using the native [Date constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date) for the date and that is not a valid date string.
You have **day-month-year**
It needs to be **year-month day**
So **1999-09-19** for that date.
I'll close as this isn't an issue for the repository code.
