### ISSUE TITLE
Could not proxy request /api/users from localhost:3000 to http://localhost:5000/

### ISSUE THREAD

**Issue by mygitH1** [bradtraversy/devconnector_2.0#31]
I got this error here below after running npm run dev.  

"Proxy error: Could not proxy request /api/users from localhost:3000 to http://localhost:5000/.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED)"

Unable to resolve it. 
Note: I made sure that the the client and server is set to 5000. Here below is a 
copy of the client code. 
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.18.0",
    "moment": "^2.24.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-moment": "^0.9.2",
    "react-redux": "^7.0.2",
    "react-router-dom": "^5.0.0",
    "react-scripts": "3.0.0",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "uuid": "^3.3.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "proxy": "http://localhost:5000"
}

server side here below:

const express = require('express');
const connectDB = require('./config/db');
const path = require('path');

const app = express();

// Connect Database
connectDB();

// Init Middleware
app.use(express.json({ extended: false }));

// Define Routes
app.use('/api/users', require('./routes/api/users'));
app.use('/api/auth', require('./routes/api/auth'));
app.use('/api/profile', require('./routes/api/profile'));
app.use('/api/posts', require('./routes/api/posts'));

// Serve static assets in production
if (process.env.NODE_ENV === 'production') {
  // Set static folder
  app.use(express.static('client/build'));

  app.get('*', (req, res) => {
    res.sendFile(path.resolve(__dirname, 'client', 'build', 'index.html'));
  });
}

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => console.log(`Server started on port ${PORT}`));

**Comment by mygitH1** [comment]
I whitelisted  0.0.0.0/0 on mondo.db and that seem to have fixed the problem. If it appears again I will come back to update.

**Comment by mygitH1** [comment]
Solved myself.

**Comment by vsthakur101** [comment]
How you solve this error.

**Comment by Chetan11-dev** [comment]
I solved it bu running server on a different terminal and client app on  a different terminal

**Comment by wejdeneBannour** [comment]
the problem with concurrently?
