### ISSUE TITLE
mobile Devconnector

### ISSUE THREAD

**Issue by dotcompot** [bradtraversy/devconnector_2.0#36]
Has anyone tried to make a mobile Devconnector?
I mean create a mobile app, and connect it to the devconnector's api and database. React Native or Flutter would be awesome!

**Comment by karlkras** [comment]
Go for it!

**Comment by HixOba** [comment]
@dotcompot, hows the mobidevconnector going? hola me?

**Comment by bushblade** [comment]
This doesn't appear to be an issue with the current repo code, more a feature request so I'm closing this as an issue.
