### ISSUE TITLE
Warning: componentWillMount has been renamed

### ISSUE THREAD

**Issue by UCAudio** [bradtraversy/devconnector_2.0#39]
I completed the course up until the deployment, and stopped to clean up various console warnings in dev tools. I was able to take care of all of them except for the following two. Does anyone know what dependency might be causing these (if one of them is the cause) or what can be done about it?

Warning: componentWillMount has been renamed, and is not recommended for use.

Warning: componentWillReceiveProps has been renamed, and is not recommended for use.

**Comment by Lucascoorek** [comment]
For me it was Moment lib for dates display. I got rid of it and display date from Mongo DB using vanilla js.

**Comment by bushblade** [comment]
As this has gone a little stale, has lack of actionable information and doesn't appear to be an issue with the current repo code, I'm closing this issue.
