### ISSUE TITLE
Comments.render

### ISSUE THREAD

**Issue by antrianis** [bradtraversy/devconnector_2.0#40]
TypeError: Cannot read property 'map' of undefined
Comments.render
src/components/scream/Comments.js:27
  24 | render() {
  25 |   const { comments, classes } = this.props;
  26 |   return (
> 27 |     <Grid container>
     | ^  28 |       {comments.map((comment, index) => {
  29 |         const { body, createdAt, userImage, userHandle } = comment;
  30 |         return (

**Comment by NguyenDa18** [comment]
Check if your comments are an array and that they are not null for that component

**Comment by bushblade** [comment]
As this has gone a little stale, has lack of actionable information and doesn't appear to be an issue with the current repo code, I'm closing this issue.
