### ISSUE TITLE
'map' undefined

### ISSUE THREAD

**Issue by yuluobin** [bradtraversy/devconnector_2.0#42]
Hey guys,

Actually I am taking the course, and I'm on lecture 52

The problem is... when I click the button to delete experience or education, web page shows 

![image](https://user-images.githubusercontent.com/23135238/66373168-fb6a3d80-e975-11e9-8239-bba585a7f0d0.png)
![image](https://user-images.githubusercontent.com/23135238/66373176-02914b80-e976-11e9-859b-d2c7c9671b8f.png)
![image](https://user-images.githubusercontent.com/23135238/66373188-0755ff80-e976-11e9-8b1c-a2c26d48b93e.png)

Well, there're three problems, but I'm sure they are related. There're some problems other students asked on the course page, but there's no solution yet. I think it is the problem of `map()`, not the `profile.js` problem, but I don't know how to correct it. 

Thanks a lot if your guys can help me! I have stuck at this for hours now.

**Comment by NguyenDa18** [comment]
Check if education is an array and is not null when the component receives it, also check if statusText exists on the err.response object.

**Comment by bushblade** [comment]
As this has gone a little stale, has lack of actionable information and doesn't appear to be an issue with the current repo code, I'm closing this issue.

**Comment by Manthan-Asher** [comment]
I was facing the same issue. Turns out that I made a really silly mistake. In the Dashboard.js I actually imported Experience and Education in the wrong way, i.e I wrote:-
import Education from './Experience'
import Experience from './Education'


Check that you might have also made the mistake.😅
