### ISSUE TITLE
Token not cleared o logout

### ISSUE THREAD

**Issue by amansadhwani** [bradtraversy/devconnector_2.0#46]
Token and User data is still present on logout .Steps to re-produce
Login with registered email id and password and click on logout .Now go to add-on redux  tools if you check  state two action were called clear_profile  and logout .If you check state user data and token are still present now If you try to login with another user for some milliseconds it will show create profile button and after that it will show experience and another details.

**Comment by Omar-Handouk** [comment]
Please paste you back-end and front end code to debug. And please format your question to make it more readable

**Comment by pvptowers** [comment]
I am having the same issue. 

When I login or register a user it is not redirecting to the dashboard page (even though the token is present and isAuthenticated set to true in Redux Dev tools.

When I click logout nothing happens either.

Code for the project is publicly available here: https://github.com/pvptowers/DevConnector-MERN

**Comment by loloDawit** [comment]
make sure 
`localStorage.removeItem('token')` is called before the return statement

**Comment by bushblade** [comment]
As this is not reproducible in the current repo code, I'll close this as an issue.
