### ISSUE TITLE
Changing the JWT tokens time doesn't redirect to login page 

### ISSUE THREAD

**Issue by amansadhwani** [bradtraversy/devconnector_2.0#47]
Steps to re-produce   go to the following path  "routes\api\auth.js"   and in jwt.sign  object change the value of expiresin to something very close ie 20seconds now after signing in after 20 seonds the page is not getting expired after refresh only it will redirect user to login page

**Comment by Omar-Handouk** [comment]
Please paste your code here. We are not able to debug without it

**Comment by bushblade** [comment]
As this has gone a little stale, has lack of actionable information and doesn't appear to be an issue with the current repo code, I'm closing this issue.
