### ISSUE TITLE
Dashboard actions has non react classes

### ISSUE THREAD

**Issue by richyrb00** [bradtraversy/devconnector_2.0#5]
https://github.com/bradtraversy/devconnector_2.0/blob/ba3c4e0b57a03d81d1515c016f052f97c820c796/client/src/components/dashboard/DashboardActions.js#L6

in dashboardActions it has several class rather than className

**Comment by richyrb00** [comment]
infact it isn't just this file there are alot of tiles containing this issue.

**Comment by bradtraversy** [comment]
I fixed that file. Feel free to make a pull request for any you see :)
