### ISSUE TITLE
src/actions/profile

### ISSUE THREAD

**Issue by amahh014** [bradtraversy/devconnector_2.0#51]
Hi everyone, I have this issue when going to 'Develo
<img width="825" alt="Screen Shot 2019-11-06 at 2 18 58 PM" src="https://user-images.githubusercontent.com/44788259/68301665-bd5d5800-00a0-11ea-8925-b626e86a48e9.png">
pers' tab, do you have any solution for this?

```
  42 |   } catch (err) {
  43 |     dispatch({
  44 |       type: PROFILE_ERROR,
> 45 |       payload: { msg: err.response.statusText, status: err.response.status }
  46 |     });
  47 |   }
  48 | };
```

also, I have an issue with  posts 

```
Posts
src/components/posts/Posts.js:9
   6 | import PostForm from './PostForm';
   7 | import { getPosts } from '../../actions/post';
   8 | 
>  9 | const Posts = ({ getPosts, post: { posts, loading } }) => {
  10 |   useEffect(() => {
  11 |     getPosts();
  12 |   }, [getPosts]);
```

**Comment by AnjasaDatta** [comment]
Hi @amahh014 ,
I have the same problem which u were facing.How did you solve this issue?Can you please tell me....
