### ISSUE TITLE
Got error with "CreateProfile" function

### ISSUE THREAD

**Issue by boongcu** [bradtraversy/devconnector_2.0#53]
I got an error as the following:

> [1] ./src/components/profile-forms/CreateProfile.js
> [1]   Line 228:   'CreateProfile' is not defined  no-undef
> [1]   Line 239:  'CreateProfile' is not defined  no-undef
> [1]
> [1] Search for the keywords to learn more about each error.
> [0] Server started on port 5000
> [0] Invalid connection string
> [0] [nodemon] app crashed - waiting for file changes before starting...

but I found it in "../../actions/profile".

**Comment by Omar-Handouk** [comment]
Please paste your code here, we are not able to debug without seeing it.

**Comment by bushblade** [comment]
As this has gone a little stale, has lack of actionable information and doesn't appear to be an issue with the current repo code, I'm closing this issue.
