### ISSUE TITLE
Option in 'express.json({...})

### ISSUE THREAD

**Issue by mafulafunk** [bradtraversy/devconnector_2.0#54]
What does the option 'extended' do?

https://github.com/bradtraversy/devconnector_2.0/blob/2a6b59a1753cac464065ed60d6655c0b68e9cf7c/server.js#L11

Can't find it in the API Reference
https://expressjs.com/de/api.html#express.json

**Comment by Omar-Handouk** [comment]
this is incorrect,
express.json() is one middleware
express.urlencoded is another

```js
app.use(express.urlencoded({extended: false}));
```

Please check: https://expressjs.com/de/api.html#express.urlencoded

**Comment by bushblade** [comment]
As this doesn't appear to be an issue with the code base I'm closing the issue.
