### ISSUE TITLE
nodejs cant connect to mongodb using mongoose

### ISSUE THREAD

**Issue by ertemishakk** [bradtraversy/devconnector_2.0#57]
hi Brad, im getting the following error when trying to connect to my mongodb. do you have any idea why?

 server running 

MongoTimeoutError: Server selection timed out after 30000 ms at Timeout._onTimeout (/Users/ishakertem/Desktop/test/node_modules/mongodb/lib/core/sdam/server_selection.js:308:9) at listOnTimeout (internal/timers.js:536:17) at processTimers (internal/timers.js:480:7) { name: 'MongoTimeoutError', }

**Comment by NguyenDa18** [comment]
@ertemishakk Did you receive the MongoURI with a Mongo Atlas connection string before starting the application? Do you have the right permissions for your created user? It should be an Atlas admin.

**Comment by ertemishakk** [comment]
yes everthing supposed to work. i realized its about the internet i am connected to. when i use a different wifi, everything works fine, however when i use my home wife, i cant connect to the database. called the isp but they didnt help me, so its not working on my network, unless you have a solution

**Comment by Omar-Handouk** [comment]
@ertemishakk The problem is with your connection or problem with a proxy setup. If it the first one you can pass an option to increase the timeout period

```js
mongoose.connect(mongoURI, {connectTimeoutMS: 3600000}) // Set connection time-out to one hours instead of 30 seconds
```

**Comment by douscriptist** [comment]
I think it may be about IP Whitelist and permissions. You should add your IP adress to whitelist from Network Access on MongoDB Atlas .
Or just allow access from anywhere as typing 0.0.0.0/0

**Comment by ertemishakk** [comment]
Problem solved. It was the service provider. As i said above, everything was working fine, and later started to crashed. Called the SP and explained it to them but they didnt understand what i said obviously, however somehow everythhing turned back to normal after few days
