### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by hayderjebur** [bradtraversy/devconnector_2.0#65]
hey guys, I am getting this "server error" I try everything I made sure the code exactly same (Server runing on port 5000
MongoDB Connected...
Illegal arguments: number, string)

**Comment by Pvybhav** [comment]
You need to apply await to your salt and password assignments too. Like this,

```
const salt = await bcrypt.genSaltSync(10);
const password = await req.body.password;
```
check the [stackoverflow](https://stackoverflow.com/questions/44871280/error-illegal-arguments-string-undefined-and-stop-server-in-node-js) for reference

**Comment by bushblade** [comment]
As this has gone a little stale, has a lack of actionable information and doesn't appear to be an issue with the current repo code, I'm closing this issue.
