### ISSUE TITLE
Register & Login

### ISSUE THREAD

**Issue by vsthakur101** [bradtraversy/devconnector_2.0#76]
I am not able to register.

**Comment by bushblade** [comment]
Hi, can you describe the steps to you take to get this issue and a little bit about your project set up and development environment please?
Have you followed the [README](https://github.com/bradtraversy/devconnector_2.0#devconnector-20) to set up and run the project? Have you set up a mongo database and have a valid connection to that database?

**Comment by vsthakur101** [comment]
Yes I followed all steps according to README.

**Comment by bushblade** [comment]
And do you have a mongo database up and running and you have a config/default.json with your mongo uri and credentials?
Please post any error output you're getting.
As of today I can successfully clone the repo, add database and run the app with no errors, so I am unable to reproduce your issue.
Can you provide a link to your projects repository or provide and example please.

**Comment by vsthakur101** [comment]
I resolve this error.
thank you very much for helping me.
