### ISSUE TITLE
Logout not possible from profile page

### ISSUE THREAD

**Issue by praveen12579** [bradtraversy/devconnector_2.0#89]
For rest end point "/user/:user_id"
e.g. http://localhost:3000/profile/5e691f0d416b0622f8148487
If user wish to logout from here,  spinner occurs for infinite time and logout does not happen.

**Comment by bushblade** [comment]
Hi, does this occur with your own code or with the repositories code?
Can you explain the steps you take to reproduce the issue?

**Comment by praveen12579** [comment]
I'm being able to reproduce with repositories code?
Probable reason is on client side while requesting "/user/:user_id" component "profile" does not fall under "PrivateRoute".
How to reproduce, run application , login, goto any profile and try to logout.

**Comment by bushblade** [comment]
Hi @praveen12579 
I can confirm your findings, thanks for logging the issue.
Yeah you're correct, not sure of the best fix as yet but I'll have a think.

**Comment by bushblade** [comment]
Ok I think this is probably the simplest solution
 ```
 const nullProfile = profile === null;
  useEffect(() => {
    getProfileById(match.params.id);
  }, [getProfileById, match.params.id, nullProfile])
```

**Comment by bushblade** [comment]
Should be fixed, I'll close but let me know if all is not as you would expect.
