### ISSUE TITLE
uuid 

### ISSUE THREAD

**Issue by Sanady** [bradtraversy/devconnector_2.0#92]
Hello, I would like to ask you something, yesterday I posted here an issue regarding uuid imports, well after my genius fix everything went down, I meant ID thing, so I restore main version of code from your github page, but error is showing once again, do you have any idea how should it be fixed?

Error:
```
./src/action/alert.js
Attempted import error: 'uuid' does not contain a default export (imported as 'uuid').
```

Best regards,
Sanady

**Comment by Sanady** [comment]
Even the code is same as yours:
```
import uuid from 'uuid';
import { SET_ALERT, REMOVE_ALERT } from './types';

export const setAlert = (msg, alertType, timeout = 5000) => dispatch => {
    const id = uuid.v4();
    dispatch({
        type: SET_ALERT,
        payload: { msg, alertType, id }
    });

    setTimeout(() => dispatch({ type: REMOVE_ALERT, payload: id }), timeout);
};
```

**Comment by bushblade** [comment]
Hi Sandy, thanks for the issue.
I've updated the uuid import in bebf49d5c560693ef1edce5039707d7fdd447b1c
This should be resolved now, pull down the changes and all should be well.

**Comment by Sanady** [comment]
But after changing this line of code this is showing up: 
`Cannot read property 'id' of undefined`

**Comment by bushblade** [comment]
Hi Sandy, where are you seeing this? Can you post your error output, it usually gives an indication as to the source of the error.
Also is this an issue you're seeing with your own project or with the code from the repository?
As of now I can clone the repo, add my config and run with no errors in the alert.

**Comment by Sanady** [comment]
Hello bush, well I see it in my console where I start my projects, so to be honest I am new to this React and stuff... I bought your udemy course so that I can learn :D

**Comment by bushblade** [comment]
Hi, if this is a problem you're facing with your own code then please post in the course Q&A with a link to your project's repository and myself or one of the other helpers will be able to help you out.
