### ISSUE TITLE
dispatch({ type: CLEAR_PROFILE }) causing user to lose their profile in actions/profile.js

### ISSUE THREAD

**Issue by devinenoise** [bradtraversy/devconnector_2.0#94]
When clicking Developers from inside the Dashboard, CLEAR_PROFILE is ran and returns that a logged in user no longer has a profile setup. 

path == src/actions/profile.js

// Get all profiles
export const getProfiles = () => async dispatch => {
  // dispatch({ type: CLEAR_PROFILE })

**Comment by bushblade** [comment]
Hi @devinenoise 
Is this a problem with your own implementation of the project or with the code here in Brad's repository?
I just tested what you're describing in the latest repo code but I can't produce any error or issue. It seems to work as expected as far as I can tell.
If this is an issue you're having in the course then please post in the course Q&A and one of us will get to you shortly.
