### ISSUE TITLE
Using proxy in client but also send api request to port 3000

### ISSUE THREAD

**Issue by DikshantNiraula** [bradtraversy/devconnector_2.0#98]
Hello Brad Traversy, 
I took your udemy course of devconnector 2 using MERN 
and I did exactly as you did but sending request using axios while login  or registration, in console it shows that it is sending request to port 3000 
like: http://localhost:3000/api/auth
Please help me with this..I spent 1 whole day to solve but no benifit.
Thank you..

**Comment by bushblade** [comment]
Hi @DikshantNiraula 
For questions and help related to the course, please post in the course Q&A
In the bowser requests will show that they go to port 3000 as that's the port the react app is running on. We do this so we don't break SOP. So to in the browser requests will go to 3000, that's the point of the proxy.
[Create React App dev server proxies the request to port 5000](https://create-react-app.dev/docs/proxying-api-requests-in-development/).
I'll close this as an issue.
