### ISSUE TITLE
setAlert is not a Function help about this isssue

### ISSUE THREAD

**Issue by jagtarsingh1232** [bradtraversy/devconnector_2.0#99]
this is my alert/actions file

import { v4 as uuidv4 } from 'uuid';
import { SET_ALERT, REMOVE_ALERT } from './types';

export const setAlert = (msg, alertType, timeout = 5000) => dispatch => {
  const id = uuidv4();
  dispatch({
    type: SET_ALERT,
    paylaod: { msg, alertType, id },
  });
  setTimeout(() => dispatch({ type: REMOVE_ALERT, paylaod: id }), timeout);
};

this is my Ragister File 

`import React, { Fragment, useState } from 'react';
//import axios from 'axios';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';
import { setAlert } from '../../actions/alert';
import PropTypes from 'prop-types';

export const Register = ({ setAlert }) => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    password2: '',
  });
  const { name, email, password, password2 } = formData;
  const onChange = e =>
    setFormData({ ...formData, [e.target.name]: e.target.value });
  const onSubmit = async e => {
    e.preventDefault();
    if (password !== password2) {
      setAlert('passowrds do not match', 'danger');
    } else {
      console.log('SUCCESS');
    }
  };
  return (
    <Fragment>
      <h1 className="large text-primary">Sign Up</h1>
      <p className="lead">
        <i className="fas fa-user" /> Create Your Account
      </p>
      <form className="form" onSubmit={e => onSubmit(e)}>
        <div className="form-group">
          <input
            type="text"
            placeholder="Name"
            name="name"
            value={name}
            onChange={e => onChange(e)}
            required
          />
        </div>
        <div className="form-group">
          <input
            type="email"
            placeholder="Email Address"
            name="email"
            value={email}
            onChange={e => onChange(e)}
          />
          <small className="form-text">
            This site uses Gravatar so if you want a profile image, use a
            Gravatar email
          </small>
        </div>
        <div className="form-group">
          <input
            type="password"
            placeholder="Password"
            name="password"
            value={password}
            onChange={e => onChange(e)}
            minLength={6}
          />
        </div>
        <div className="form-group">
          <input
            type="password"
            placeholder="Confirm Password"
            name="password2"
            value={password2}
            onChange={e => onChange(e)}
            minLength={6}
          />
        </div>
        <input
          type="submit"
          className="btn btn-primary"
          defaultValue="Register"
        />
      </form>
      <p className="my-1">
        Already have an account? <Link to="/login">Login In</Link>
      </p>
    </Fragment>
  );
};

Register.propType = {
  setAlert: PropTypes.func.isRequired,
};
export default connect(null, { setAlert })(Register);

**Comment by bushblade** [comment]
Hi @jagtarsingh1232 
Your issue is that you're not using the default export.
You have both a named export - `export const Register` and a default export.
You need to be using the default export as that is the one that is connected to redux.
For questions related to the course please post in the course Q&A as the issue tracker here is just for issues with the code base in the repository.
As there is no issue here I will close.
